### ISSUE TITLE
Arbitrary overflow cutoff (which doesn't actually work)

### ISSUE THREAD

**Issue by ZapDotZip** [Kawoo1/RustProjects#3]
```
Enter your choice: 1
Enter the first number: 2147483640
Enter the second number: 3
Overflow error
```
The code arbitrarily limits the answer at 99999999. The maximum size for an i32 is 2147483647. So 2147483647 - 99999999 = 2,047,483,648. And 2,047,483,648 / 2147483647 = 0.9534338717.

You are limiting your calculator to approximately 4.66% of the available answer range.

Not to mention that this does not actually solve an overflow error:
```
Enter your choice: 1
Enter the first number: 2147483640
Enter the second number: 8
thread 'main' panicked at 'attempt to add with overflow', mainCalculator.rs:21:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You can see the limits for i32 [here](https://doc.rust-lang.org/std/primitive.i32.html), though I suggest you use [i64](https://doc.rust-lang.org/std/primitive.i64.html) for your calculator.

Oh, and don't forget about negative numbers!
```
Enter your choice: 2
Enter the first number: -2147483640
Enter the second number: 9
thread 'main' panicked at 'attempt to subtract with overflow', mainCalculator.rs:22:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kawoo1** [comment]
Updated the scope of the calculator to better handle the overflow error. Updated to suggested <i64>. Negative numbers clause has not been debugged. Will complete in a future patch
